/**
 * LOCKDOWN — Anchor-Based Sprite Alignment System
 *
 * This module handles rendering paired grappling sprites using anchor points
 * to ensure characters always look physically connected regardless of which
 * character combination is being displayed.
 *
 * Integration: Import this into your existing game engine and call
 * renderPosition() whenever the game state changes position.
 */

// ============================================================
// ANCHOR DATA — Generated by the Python pipeline
// Replace this with your actual anchor_manifest.json data
// ============================================================

const ANCHOR_MANIFEST = {
  closed_guard: {
    position: "closed_guard",
    image_size: { width: 160, height: 160 },
    characters: {
      marcus: { sprite_file: "closed_guard_marcus.png", role: "top" },
      yuki: { sprite_file: "closed_guard_yuki.png", role: "bottom" }
    },
    anchor_regions: [
      { center_x: 80, center_y: 55, suggested_name: "upper_contact", pixel_count: 45 },
      { center_x: 78, center_y: 95, suggested_name: "lower_contact", pixel_count: 62 }
    ],
    contact_center: { x: 79, y: 75 }
  },
  open_guard: {
    position: "open_guard",
    image_size: { width: 160, height: 160 },
    characters: {
      marcus: { sprite_file: "open_guard_marcus.png", role: "top" },
      yuki: { sprite_file: "open_guard_yuki.png", role: "bottom" }
    },
    anchor_regions: [
      { center_x: 75, center_y: 70, suggested_name: "upper_contact", pixel_count: 30 },
      { center_x: 80, center_y: 100, suggested_name: "lower_contact", pixel_count: 40 }
    ],
    contact_center: { x: 78, y: 85 }
  },
  // ... (populated from your anchor_manifest.json after running the pipeline)
};

// ============================================================
// SPRITE CACHE — Preloads all character sprites
// ============================================================

class SpriteCache {
  constructor() {
    this.cache = {};
    this.loading = {};
  }

  /**
   * Preload all sprites from the manifest
   * @param {string} basePath - Path to sprite directory
   * @param {object} manifest - The anchor manifest
   */
  async preloadAll(basePath, manifest) {
    const promises = [];

    for (const [posName, posData] of Object.entries(manifest)) {
      for (const [charKey, charData] of Object.entries(posData.characters)) {
        const key = `${posName}_${charKey}`;
        const path = `${basePath}/${posName}/${charData.sprite_file}`;
        promises.push(this.load(key, path));
      }
    }

    await Promise.all(promises);
    console.log(`SpriteCache: Loaded ${Object.keys(this.cache).length} sprites`);
  }

  /**
   * Load a single sprite
   */
  load(key, path) {
    if (this.cache[key]) return Promise.resolve(this.cache[key]);

    if (!this.loading[key]) {
      this.loading[key] = new Promise((resolve, reject) => {
        const img = new Image();
        img.onload = () => {
          this.cache[key] = img;
          delete this.loading[key];
          resolve(img);
        };
        img.onerror = () => {
          console.warn(`Failed to load sprite: ${path}`);
          delete this.loading[key];
          reject(new Error(`Failed to load: ${path}`));
        };
        img.src = path;
      });
    }

    return this.loading[key];
  }

  /**
   * Get a cached sprite
   */
  get(positionName, characterKey) {
    return this.cache[`${positionName}_${characterKey}`] || null;
  }
}


// ============================================================
// POSITION RENDERER — Handles aligned sprite rendering
// ============================================================

class PositionRenderer {
  /**
   * @param {HTMLCanvasElement} canvas - The game canvas
   * @param {SpriteCache} spriteCache - Preloaded sprite cache
   * @param {object} manifest - Anchor manifest data
   */
  constructor(canvas, spriteCache, manifest) {
    this.canvas = canvas;
    this.ctx = canvas.getContext('2d');
    this.spriteCache = spriteCache;
    this.manifest = manifest;

    // Rendering config
    this.displayScale = 2;  // Scale up pixel art (NEAREST neighbor)
    this.arenaCenter = { x: canvas.width / 2, y: canvas.height / 2 };

    // Disable anti-aliasing for crisp pixel art
    this.ctx.imageSmoothingEnabled = false;
  }

  /**
   * Render a grappling position with two characters aligned by anchors.
   *
   * @param {string} positionName - e.g., "mount", "closed_guard"
   * @param {string} topCharacter - Character key for top/aggressor role
   * @param {string} bottomCharacter - Character key for bottom/defender role
   * @param {object} options - Optional overrides { offsetX, offsetY, scale }
   */
  renderPosition(positionName, topCharacter, bottomCharacter, options = {}) {
    const posData = this.manifest[positionName];
    if (!posData) {
      console.warn(`Unknown position: ${positionName}`);
      return;
    }

    const scale = options.scale || this.displayScale;
    const offsetX = options.offsetX || 0;
    const offsetY = options.offsetY || 0;

    // Determine which character was originally top/bottom in the generated sprite
    const originalTop = Object.entries(posData.characters)
      .find(([k, v]) => v.role === "top")?.[0];
    const originalBottom = Object.entries(posData.characters)
      .find(([k, v]) => v.role === "bottom")?.[0];

    // Get sprites — use the requested characters in the requested roles
    // If the characters are swapped from the original, we may need to flip
    const topSprite = this.spriteCache.get(positionName, topCharacter);
    const bottomSprite = this.spriteCache.get(positionName, bottomCharacter);

    if (!topSprite || !bottomSprite) {
      console.warn(`Missing sprites for ${positionName}: top=${topCharacter}, bottom=${bottomCharacter}`);
      return;
    }

    // Calculate render position — center on arena
    const imgW = posData.image_size.width * scale;
    const imgH = posData.image_size.height * scale;
    const renderX = this.arenaCenter.x - imgW / 2 + offsetX;
    const renderY = this.arenaCenter.y - imgH / 2 + offsetY;

    // Render bottom character first (they're underneath)
    this.ctx.save();
    this.ctx.imageSmoothingEnabled = false;

    this.ctx.drawImage(
      bottomSprite,
      renderX, renderY,
      imgW, imgH
    );

    // Render top character on top
    this.ctx.drawImage(
      topSprite,
      renderX, renderY,
      imgW, imgH
    );

    this.ctx.restore();
  }

  /**
   * Render a transition between two positions.
   * This triggers the screen shake + overlay and swaps sprites.
   *
   * @param {string} fromPosition - Current position
   * @param {string} toPosition - Target position
   * @param {string} topCharacter - Who's on top in the new position
   * @param {string} bottomCharacter - Who's on bottom in the new position
   * @param {string} moveText - Text to display during transition (e.g., "SWEEP!")
   * @param {function} onComplete - Callback when transition finishes
   */
  async transitionPosition(fromPosition, toPosition, topCharacter, bottomCharacter,
                            moveText, onComplete) {
    // Phase 1: Flash + shake (hides the sprite swap)
    await this.playTransitionEffect(moveText);

    // Phase 2: Render new position (instant swap during the visual effect)
    this.renderPosition(toPosition, topCharacter, bottomCharacter);

    // Phase 3: Settle
    if (onComplete) onComplete();
  }

  /**
   * Play the transition visual effect — screen shake + flash + text overlay.
   * Customize this to match your existing effect system.
   */
  playTransitionEffect(moveText) {
    return new Promise((resolve) => {
      const duration = 800; // ms
      const startTime = performance.now();

      const animate = (currentTime) => {
        const elapsed = currentTime - startTime;
        const progress = Math.min(elapsed / duration, 1);

        // Screen shake (decaying)
        const shakeIntensity = Math.max(0, 1 - progress) * 6;
        const shakeX = (Math.random() - 0.5) * shakeIntensity;
        const shakeY = (Math.random() - 0.5) * shakeIntensity;
        this.canvas.style.transform = `translate(${shakeX}px, ${shakeY}px)`;

        // Flash overlay (peaks at 30%, fades out)
        if (progress < 0.3) {
          const flashAlpha = progress / 0.3 * 0.4;
          this.ctx.fillStyle = `rgba(255, 255, 255, ${flashAlpha})`;
          this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
        } else if (progress < 0.6) {
          const flashAlpha = (1 - (progress - 0.3) / 0.3) * 0.4;
          this.ctx.fillStyle = `rgba(255, 255, 255, ${flashAlpha})`;
          this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
        }

        // Text overlay (appears at 20%, stays until 80%)
        if (progress > 0.2 && progress < 0.8 && moveText) {
          this.ctx.save();
          this.ctx.font = 'bold 24px "Press Start 2P", monospace';
          this.ctx.textAlign = 'center';
          this.ctx.fillStyle = '#FFD700';
          this.ctx.strokeStyle = '#000';
          this.ctx.lineWidth = 3;

          const textY = this.arenaCenter.y - 60;
          this.ctx.strokeText(moveText, this.arenaCenter.x, textY);
          this.ctx.fillText(moveText, this.arenaCenter.x, textY);
          this.ctx.restore();
        }

        if (progress < 1) {
          requestAnimationFrame(animate);
        } else {
          this.canvas.style.transform = 'none';
          resolve();
        }
      };

      requestAnimationFrame(animate);
    });
  }

  /**
   * Get anchor point data for a position (useful for UI overlays, health bars, etc.)
   */
  getAnchorPoints(positionName) {
    const posData = this.manifest[positionName];
    if (!posData) return null;

    return {
      center: posData.contact_center,
      regions: posData.anchor_regions,
      imageSize: posData.image_size
    };
  }
}


// ============================================================
// INTEGRATION HELPER — Quick setup for your game
// ============================================================

/**
 * Quick setup function. Call this during game initialization.
 *
 * Usage:
 *   const renderer = await initSpriteSystem('canvas-id', '/sprites/separated/');
 *   renderer.renderPosition('mount', 'marcus', 'yuki');
 */
async function initSpriteSystem(canvasId, spritePath, customManifest = null) {
  const canvas = document.getElementById(canvasId);
  if (!canvas) throw new Error(`Canvas not found: ${canvasId}`);

  // Load manifest
  let manifest = customManifest;
  if (!manifest) {
    try {
      const response = await fetch(`${spritePath}/anchor_manifest.json`);
      manifest = await response.json();
    } catch (e) {
      console.warn('Could not load anchor_manifest.json, using built-in defaults');
      manifest = ANCHOR_MANIFEST;
    }
  }

  // Preload sprites
  const cache = new SpriteCache();
  await cache.preloadAll(spritePath, manifest);

  // Create renderer
  const renderer = new PositionRenderer(canvas, cache, manifest);

  return renderer;
}


// ============================================================
// EXPORTS (adjust based on your module system)
// ============================================================

// For ES modules:
// export { SpriteCache, PositionRenderer, initSpriteSystem, ANCHOR_MANIFEST };

// For browser globals:
if (typeof window !== 'undefined') {
  window.LOCKDOWN_SPRITES = {
    SpriteCache,
    PositionRenderer,
    initSpriteSystem,
    ANCHOR_MANIFEST
  };
}
